### ISSUE TITLE
如何取消首行缩进，并增加段落间距？

### ISSUE THREAD

**Issue by VimWei** [chengjun90/markdown2pdf#1]
首先感谢提供这么好的template！

为了更好地展示中英混排，我不希望采用中式的首行缩进，而是采用段落之间增加间距的形式，不知该如何修改template?

**Comment by chengjun90** [comment]
可以直接修改**template.tex**文件。
例如：
```latex
% 版式设置
\ctexset{
	autoindent=0em  %首行缩进字符数
}
\setlength{\parskip}{2.0ex} % 段间距
```
这段代码放在导言区即可。
![default](https://user-images.githubusercontent.com/17266885/51950594-104c1400-246c-11e9-8b01-c306dfc8752c.png)

**Comment by VimWei** [comment]
太好了！Thanks!
